server:
  port: 8625
sa-token:
  token-name: token
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-log: false
 # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
spring:
  codec:
    max-in-memory-size: 1048576
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  profiles:
    active: @spring.profiles.active@
  data:
    redis:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
